# Generated by Django 4.2.20 on 2025-03-18 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='api.job'),
        ),
    ]
