# Generated by Django 4.2.20 on 2025-03-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_box_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_full',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='size',
            field=models.CharField(max_length=1),
        ),
    ]
