# Generated by Django 4.2.20 on 2025-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_box_box_full_alter_box_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='box',
            name='size',
            field=models.CharField(choices=[('1', 'Small'), ('2', 'Medium'), ('3', 'Large'), ('4', 'Extra Large')], default='1', max_length=1),
        ),
    ]
