# Generated by Django 4.2.20 on 2025-03-20 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_created_at_item_is_fragile_item_is_heavy'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='box_description',
            field=models.TextField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='is_fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='box',
            name='is_heavy',
            field=models.BooleanField(default=False),
        ),
    ]
